---
kind: pipeline
name: build
type: docker

trigger:
  branch:
    include:
      - main
  event:
    include:
      - push

concurrency:
  limit: 1

steps:
- name: php
  image: lbausch/laravel-ci:php82
  commands:
  - make composer

- name: js
  image: lbausch/laravel-ci:php82
  commands:
  - npm i -g yarn
  - make js

- name: rsync
  image: drillster/drone-rsync
  settings:
    hosts: [10.10.0.23]
    user: doeggscostmore.com
    key:
      from_secret: deploy_key
    port: 2222
    target: /var/www/html/
    exclude:
      - "./storage/"
      - "./static/"
    source: ./*
    delete: true
    recursive: true

- name: deploy
  image: appleboy/drone-ssh
  settings:
    host:
      - 10.10.0.23
    username: doeggscostmore.com
    key:
      from_secret: deploy_key
    port: 2222
    command_timeout: 5m
    script: |
     cd /var/www/html && bash deploy.sh export

- name: cache
  image: alpine
  environment:
    CF_API_KEY:
      from_secret: cf_api_key
    CF_EMAIL:
      from_secret: cf_email
    ZONE_ID:
      from_secret: zone_id

  commands:
    - apk add --update bash curl
    - bash purge.sh

---
kind: pipeline
name: build-staging
type: docker

trigger:
  branch:
    include:
      - staging

concurrency:
  limit: 1

steps:
- name: php
  image: lbausch/laravel-ci:php82
  commands:
  - make composer-dev

- name: js
  image: lbausch/laravel-ci:php82
  commands:
  - npm i -g yarn
  - make js

# - name: test
#   image: lbausch/laravel-ci:php82
#   commands:
#   - make test-ci

- name: rsync
  image: drillster/drone-rsync
  settings:
    hosts: [10.10.0.23]
    user: staging.doeggscostmore.com
    key:
      from_secret: deploy_key
    port: 2222
    target: /var/www/html/
    exclude:
      - "./storage/"
      - "./static/"
    source: ./*
    delete: true
    recursive: true
  when:
    branch:
      include:
        - staging
    event:
      exclude:
        - pull_request

- name: deploy
  image: appleboy/drone-ssh
  settings:
    host:
      - 10.10.0.23
    username: staging.doeggscostmore.com
    key:
      from_secret: deploy_key
    port: 2222
    command_timeout: 5m
    script: |
     cd /var/www/html && bash deploy.sh
  when:
    branch:
      include:
        - staging
    event:
      exclude:
        - pull_request
