---
kind: pipeline
name: build
type: docker

trigger:
  branch:
    include:
      - master
  event:
    include:
      - pull_request

concurrency:
  limit: 1

steps:
- name: laravel
  image: lbausch/laravel-ci:php82
  commands:
  - make composer

- name: node
  image: lbausch/laravel-ci:php82
  commands:
  - npm i -g yarn
  - make js

- name: rsync
  image: drillster/drone-rsync
  settings:
    hosts: [10.10.0.23]
    user: doeggscostmore.com
    key:
      from_secret: deploy_key
    port: 2222
    target: /home/web/html/
    source: ./*
    delete: true
    recursive: true
  when:
    branch:
      include:
        - master
    event:
      exclude:
        - pull_request

- name: deploy
  image: appleboy/drone-ssh
  settings:
    host:
      - 10.10.0.23
    username: doeggscostmore.com
    key:
      from_secret: deploy_key
    port: 2222
    command_timeout: 5m
    script: |
      cp /home/web/.env /home/web/html/.env &&
      cd /home/web/html &&
      php artisan config:cache &&
      php artisan migrate &&
      php artisan cache:clear
  when:
    branch:
      include:
        - master
    event:
      exclude:
        - pull_request
